
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: postula_app

  username: cristobal
  password: admin1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: postula_app_test

  username: cristobal
  password: admin1234
  host: localhost
  port: 5432


production:
  <<: *default
  database: postula_app_production
  username: postula_app
  password: <%= ENV["POSTULA_APP_DATABASE_PASSWORD"] %>
